"""Render the doctor's output: report.md (human) and findings.json
(machine, diffable across sessions thanks to the stable finding ids).
Layout follows PLAN.md section 7; trend table and plots arrive in later
phases.
"""
from __future__ import annotations

import datetime as _dt
import json

from . import timeutil
from .findings import SEVERITY_ORDER, Finding, banner
from .session import Session


def _fmt_evidence(ev: dict) -> str:
    parts = []
    for k, v in ev.items():
        parts.append(f"{k}={json.dumps(v, default=str)}")
    return ", ".join(parts)


def _axis_table(s: Session) -> list[str]:
    r = s.report
    if r is None or not r.final_gains:
        return []
    lines = [
        "| axis | entry kx/kv | final kx/kv | result | alpha [CI] | lag ms | PM nom/worst |",
        "|---|---|---|---|---|---|---|",
    ]
    # entry gains from the log baselines when present (the report only
    # carries the final set).
    base = {}
    if s.log:
        base = {e.fields["axis"]: e.fields for e in s.log.all("baseline_gains")}
    for ax in ("x", "y", "z"):
        fg = r.final_gains.get(ax)
        if not fg:
            continue
        b = base.get(ax)
        entry = f"{b['kx']:.2f}/{b['kv']:.2f}" if b else "?"
        final = f"{fg.get('kx', float('nan')):.2f}/{fg.get('kv', float('nan')):.2f}"
        result = fg.get("result") or ("validated" if fg.get("validated")
                                      else "kept")
        alpha = fg.get("alpha")
        ci = fg.get("alpha_ci")
        alpha_s = (f"{alpha:.2f} [{ci[0]:.2f}, {ci[1]:.2f}]"
                   if alpha is not None and ci else "?")
        lag = f"{fg.get('lag_ms', '?')}"
        pm = (f"{fg.get('pm_nominal_deg', '?')}/{fg.get('pm_worst_deg', '?')}")
        lines.append(f"| {ax} | {entry} | {final} | {result} | {alpha_s} | {lag} | {pm} |")
    if r.final_yawctrl_tau is not None:
        b = s.log.first("baseline_yaw") if s.log else None
        entry = f"tau {b.fields['tau']:.2f}" if b else "?"
        lines.append(f"| yaw | {entry} | tau {r.final_yawctrl_tau:.2f} | "
                     f"{r.yaw_result or '-'} | | | |")
    return lines


def render_markdown(s: Session, findings: list[Finding],
                    recommendations: list[dict],
                    plots: list[str] | None = None,
                    history_md: list[str] | None = None) -> str:
    verdict, why = banner(findings)
    art = s.artifacts
    out = [f"# Tuning session {s.name} — {verdict}", "", why, ""]

    out += ["## Session facts", ""]
    facts = [
        ("session start", timeutil.fmt_both_clocks(art.start)),
        ("report written", timeutil.fmt_both_clocks(art.end)),
    ]
    if s.report:
        r = s.report
        facts += [
            ("generation", r.generation),
            ("status", r.status),
            ("duration", f"{r.session_duration_s:.1f} s"
             if r.session_duration_s else "?"),
            ("rounds", str(r.rounds_flown) if r.rounds_flown else "-"),
            ("episodes", str(len(r.step_episodes))),
        ]
        if r.diagnosis:
            facts.append(("diagnosis", r.diagnosis))
    for label, val in facts:
        out.append(f"- **{label}:** {val}")
    out.append("")

    table = _axis_table(s)
    if table:
        out += ["## Per-axis outcome", ""] + table + [""]

    out += ["## Findings", ""]
    for sev in SEVERITY_ORDER:
        group = [f for f in findings if f.severity == sev]
        if not group:
            continue
        out.append(f"### {sev}")
        out.append("")
        for f in group:
            ax = f" [{f.axis}]" if f.axis else ""
            out.append(f"- **{f.id}**{ax}: {f.title}")
            if f.evidence:
                out.append(f"  - evidence: {_fmt_evidence(f.evidence)}")
            if f.source:
                out.append(f"  - source: {'; '.join(f.source)}")
            if f.explanation:
                out.append(f"  - {f.explanation}")
        out.append("")

    if recommendations:
        out += ["## Recommendations", ""]
        for i, rec in enumerate(recommendations, 1):
            trig = ", ".join(rec["triggered_by"])
            out.append(f"{i}. {rec['text']} _(triggered by: {trig})_")
        out.append("")

    if history_md:
        out += history_md

    if plots:
        out += ["## Plots", ""]
        for name in plots:
            out.append(f"![{name}](plots/{name})")
        out.append("")

    out.append(f"---\ngenerated by geo-tuner-doctor at "
               f"{_dt.datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %z')}")
    return "\n".join(out) + "\n"


def render_json(s: Session, findings: list[Finding],
                recommendations: list[dict]) -> str:
    verdict, why = banner(findings)
    doc = {
        "session": s.name,
        "report": str(s.artifacts.report),
        "verdict": verdict,
        "verdict_why": why,
        "generated": _dt.datetime.now().astimezone().isoformat(timespec="seconds"),
        "findings": [f.to_dict() for f in findings],
        "recommendations": recommendations,
    }
    return json.dumps(doc, indent=1, default=str) + "\n"
